# Generated by Django 5.2.6 on 2026-02-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Warehouse",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=255, unique=True)),
                        ("organization", models.CharField(blank=True, max_length=255, null=True)),
                        ("address", models.CharField(blank=True, max_length=255, null=True)),
                        ("phone_number", models.CharField(blank=True, max_length=20, null=True)),
                        ("directions", models.ImageField(blank=True, null=True, upload_to="maps")),
                    ],
                    options={
                        "db_table": "catalog_warehouse",
                    },
                ),
            ],
            database_operations=[],
        )
    ]
