# Generated by Django 5.2.6 on 2026-02-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_warehouse_contacts_warehouse_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='contacts',
        ),
    ]
