# Generated by Django 5.2.6 on 2026-03-12 06:02

import phonenumber_field.modelfields
import phonenumber_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_warehouse_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
