# Generated by Django 5.2.6 on 2026-03-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_warehouse_phone_number_warehouse_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
