# Generated by Django 5.2.6 on 2026-03-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_warehouse_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
    ]
