# Generated by Django 5.2.6 on 2026-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_warehouse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
