# Generated by Django 5.2.17 on 2026-08-30 14:16

import core.validators.files
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_warehouse_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='directions',
            field=models.ImageField(blank=True, null=True, upload_to='maps', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), core.validators.files.validate_image_file_size]),
        ),
    ]
