# Generated by Django 5.2.6 on 2026-02-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('piece', 'шт'), ('kilogram', 'кг'), ('ton', 'т'), ('pallet', 'пал'), ('%', '%'), ('millimeter', 'мм'), ('megapascal', 'МПа'), ('litre', 'л'), ('kg/m3', 'кг/м3')], max_length=20, unique=True)),
                ('is_weight_based', models.BooleanField(default=False)),
                ('to_kg_factor', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'catalog_unit',
            },
        ),
        migrations.CreateModel(
            name='DescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Description Item',
                'verbose_name_plural': 'Description Items',
                'db_table': 'catalog_description_item',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('bags_per_pallet', models.PositiveSmallIntegerField(null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Specification Group',
                'verbose_name_plural': 'Specification Groups',
                'db_table': 'catalog_specification_group',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_items', to='catalog.descriptionitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Description',
                'verbose_name_plural': 'Product Descriptions',
                'db_table': 'catalog_product_description',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.ManyToManyField(related_name='product', through='catalog.ProductDescription', to='catalog.descriptionitem'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'db_table': 'catalog_product_group',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_per_unit', models.SmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.appunit')),
            ],
            options={
                'db_table': 'catalog_product_units',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.ManyToManyField(through='catalog.ProductUnit', to='catalog.appunit'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_items', to='catalog.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spec_items', to='catalog.appunit')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_items', to='catalog.specificationgroup')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'db_table': 'catalog_specification',
            },
        ),
        migrations.AddConstraint(
            model_name='productdescription',
            constraint=models.UniqueConstraint(fields=('product', 'description_item'), name='uniq_product_description'),
        ),
        migrations.AddConstraint(
            model_name='productgroup',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_product_group'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('product', 'units'), name='uniq_product_unit'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'group'), name='uniq_product_spec_group'),
        ),
    ]
