# Generated by Django 5.2.6 on 2026-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_web',
            field=models.BooleanField(default=False),
        ),
    ]
