# Generated by Django 5.2.6 on 2026-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_warehouse_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appunit',
            name='title',
            field=models.CharField(choices=[('piece', 'шт'), ('kilogram', 'кг'), ('ton', 'т'), ('pallet', 'пал'), ('%', '%'), ('millimeter', 'мм'), ('megapascal', 'МПа'), ('litre', 'л'), ('kg/m3', 'кг/м3')], max_length=20),
        ),
    ]
