# Generated by Django 5.2.6 on 2026-02-11 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_appunit_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_per_pallet', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Product Pallet',
                'verbose_name_plural': 'Product Pallets',
                'ordering': ['product', 'warehouse'],
            },
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ('group__order', 'order', 'id'), 'verbose_name': 'Product Specification', 'verbose_name_plural': 'Product Specifications'},
        ),
        migrations.RemoveConstraint(
            model_name='productdescription',
            name='uniq_product_description',
        ),
        migrations.RemoveConstraint(
            model_name='productspecification',
            name='uniq_product_spec_group',
        ),
        migrations.RemoveConstraint(
            model_name='productunit',
            name='uniq_product_unit',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='price',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='productdescription',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bags_per_pallet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_unit',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='description_item',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='units',
        ),
        migrations.AddField(
            model_name='descriptionitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_piece_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_descriptions', to='catalog.descriptionitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdescription',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='name',
            field=models.CharField(default='Specification', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecification',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productunit',
            name='unit',
            field=models.ForeignKey(default=1, limit_choices_to={'title': 'piece'}, on_delete=django.db.models.deletion.PROTECT, to='catalog.appunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationgroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appunit',
            name='title',
            field=models.CharField(choices=[('piece', 'шт'), ('kilogram', 'кг'), ('ton', 'т'), ('pallet', 'пал'), ('%', '%'), ('millimeter', 'мм'), ('megapascal', 'МПа'), ('litre', 'л'), ('kg/m3', 'кг/м3')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='appunit',
            name='to_kg_factor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_specs', to='catalog.specificationgroup'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.appunit'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='kg_per_unit',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piece_config', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['product', 'group', 'order'], name='catalog_spe_product_fc6454_idx'),
        ),
        migrations.AddConstraint(
            model_name='productdescription',
            constraint=models.UniqueConstraint(fields=('product', 'item'), name='uniq_product_description'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'group', 'name'), name='uniq_product_spec_row_in_group'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(('kg_per_unit__in', [15, 20, 25, 30])), name='chk_piece_kg_allowed'),
        ),
        migrations.AddField(
            model_name='productpallet',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pallets', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productpallet',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_pallets', to='catalog.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='productpallet',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='uniq_product_warehouse_pallet'),
        ),
    ]
