# Generated by Django 5.2.6 on 2026-02-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productpallet_alter_productspecification_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceHistory',
            new_name='PurchasePriceHistory',
        ),
        migrations.AlterModelOptions(
            name='purchasepricehistory',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Purchase Price History', 'verbose_name_plural': 'Purchase Price History'},
        ),
        migrations.AlterField(
            model_name='product',
            name='is_piece_based',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='purchasepricehistory',
            table='catalog_purchase_price_history',
        ),
    ]
