# Generated by Django 5.2.6 on 2026-02-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_pricehistory_purchasepricehistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='productgroup',
            name='uniq_product_group',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='product_groups', to='catalog.productgroup'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_product_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_group', 'name'), name='uniq_product_group_name'),
        ),
    ]
