# Generated by Django 5.2.6 on 2026-02-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Product Specification Name',
                'verbose_name_plural': 'Product Specification Names',
                'db_table': 'catalog_product_spec_name',
                'ordering': ('group__order', 'order'),
            },
        ),
        migrations.AlterModelOptions(
            name='descriptionitem',
            options={'ordering': ('order',), 'verbose_name': 'Description Item', 'verbose_name_plural': 'Description Items'},
        ),
        migrations.AlterModelOptions(
            name='productdescription',
            options={'ordering': ('item__order',), 'verbose_name': 'Product Description', 'verbose_name_plural': 'Product Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Product Specification', 'verbose_name_plural': 'Product Specifications'},
        ),
        migrations.RemoveConstraint(
            model_name='productspecification',
            name='uniq_product_spec_row_in_group',
        ),
        migrations.RemoveIndex(
            model_name='productspecification',
            name='catalog_spe_product_fc6454_idx',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='group',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecname',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.specificationgroup'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_names', to='catalog.productspecname'),
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['product', 'order'], name='catalog_spe_product_cfd5f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_product_spec_row'),
        ),
    ]
