# Generated by Django 5.2.6 on 2026-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productspecname_alter_descriptionitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ('name__group__order', 'name__order', 'pk'), 'verbose_name': 'Product Specification', 'verbose_name_plural': 'Product Specifications'},
        ),
        migrations.RemoveIndex(
            model_name='productspecification',
            name='catalog_spe_product_cfd5f6_idx',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='order',
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['product'], name='catalog_spe_product_1e509d_idx'),
        ),
    ]
