# Generated by Django 5.2.6 on 2026-02-17 11:12
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_productspecification_options_and_more"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasepricehistory",
            name="warehouse",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price',to='stock.warehouse'),
        ),
        migrations.AlterField(
            model_name="productpallet",
            name="warehouse",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_pallets',to='stock.warehouse'),
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="Warehouse"),
            ],
            database_operations=[],
        ),
    ]

