# Generated by Django 5.2.6 on 2026-03-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_purchasepricehistory_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appunit',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
    ]
