# Generated by Django 5.2.6 on 2026-04-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_appunit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product')),
            ],
            options={
                'verbose_name': 'История цен',
                'verbose_name_plural': 'История цен',
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
