# Generated by Django 5.2.6 on 2026-04-23 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productpricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionitem',
            options={'ordering': ('order',), 'verbose_name': 'Пункт описания', 'verbose_name_plural': 'Пункты описания'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name': 'Группа материалов', 'verbose_name_plural': 'Группы материалов'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ('name__group__order', 'name__order', 'pk'), 'verbose_name': 'Значение показателя спецификации', 'verbose_name_plural': 'Значения показателей спецификации'},
        ),
        migrations.AlterModelOptions(
            name='productspecname',
            options={'ordering': ('group__order', 'order'), 'verbose_name': 'Наименование показателя спецификации', 'verbose_name_plural': 'Наименования показателей спецификации'},
        ),
        migrations.AlterModelOptions(
            name='specificationgroup',
            options={'verbose_name': 'Группа показателей спецификации', 'verbose_name_plural': 'Группы показателей спецификации'},
        ),
        migrations.RemoveConstraint(
            model_name='productunit',
            name='chk_piece_kg_allowed',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='kg_per_unit',
        ),
        migrations.AddField(
            model_name='productunit',
            name='value',
            field=models.PositiveSmallIntegerField(default=1, help_text='Вес мешка (кг) или кол-во в паллете (шт)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_configs', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.appunit'),
        ),
        migrations.AlterModelTable(
            name='productunit',
            table=None,
        ),
    ]
