# Generated by Django 5.2.6 on 2026-04-23 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_descriptionitem_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpallet',
            options={'verbose_name': 'Паллета (складская)', 'verbose_name_plural': 'Паллеты (складские)'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'verbose_name': 'Единица измерения товара', 'verbose_name_plural': 'Единицы измерения товаров'},
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_config', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'title__in': ['piece', 'ton']}, on_delete=django.db.models.deletion.PROTECT, to='catalog.appunit'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='value',
            field=models.PositiveSmallIntegerField(help_text='Вес мешка (кг) или 1 для тонны'),
        ),
        migrations.AlterField(
            model_name='purchasepricehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='ProductPriceHistory',
        ),
    ]
