# Generated by Django 5.2.6 on 2026-04-27 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productpallet_options_and_more'),
        ('order', '0007_order_samples_orderitem_price_at_sale'),
        ('stock', '0007_warehouse_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasepricehistory',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'История цены закупки', 'verbose_name_plural': 'История цен закупки'},
        ),
        migrations.AlterField(
            model_name='purchasepricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_price_history', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='purchasepricehistory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasepricehistory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_prices', to='stock.warehouse'),
        ),
        migrations.CreateModel(
            name='SalesPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_prices', to='order.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_price_history', to='catalog.product')),
            ],
            options={
                'verbose_name': 'История цены реализации',
                'verbose_name_plural': 'История цен реализации',
                'db_table': 'catalog_sales_price_history',
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'unique_together': {('product', 'client', 'date')},
            },
        ),
    ]
