# Generated by Django 5.2.6 on 2026-04-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_purchasepricehistory_options_and_more'),
        ('order', '0008_packtype_orderitem_pack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_pack', to='order.packtype'),
        ),
    ]
