# Generated by Django 5.2.6 on 2026-05-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_default_pack'),
        ('order', '0009_orderdelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespricehistory',
            options={
                'ordering': ['-date'],
                'verbose_name': 'История цены реализации',
                'verbose_name_plural': 'История цен реализации',
            },
        ),

        migrations.AddField(
            model_name='salespricehistory',
            name='customer',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='customer_prices',
                to='order.customer',
            ),
            preserve_default=False,
        ),

        migrations.AlterUniqueTogether(
            name='salespricehistory',
            unique_together={('product', 'customer', 'date')},
        ),

        migrations.RemoveField(
            model_name='salespricehistory',
            name='client',
        ),
    ]