# Generated by Django 5.2.17 on 2026-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='value',
            field=models.PositiveSmallIntegerField(help_text='Вес упаковки (кг) или 1 для тонны'),
        ),
    ]
