# Generated by Django 5.2.17 on 2026-09-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_productunit_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appunit',
            name='title',
            field=models.CharField(choices=[('piece', 'шт'), ('kilogram', 'кг'), ('ton', 'т'), ('pallet', 'пал'), ('%', '%'), ('millimeter', 'мм'), ('megapascal', 'МПа'), ('litre', 'л'), ('kg/m3', 'кг/м3'), ('kg/m2', 'кг/м2'), ('Bk/kg', 'Бк/кг')], max_length=20, unique=True),
        ),
    ]
