# Generated by Django 5.2.6 on 2026-02-23 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(help_text='Russian phone number', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message="Format: '+79991234567' or '89991234567'. Exactly 10 digits required after prefix.", regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')]),
        ),
    ]
