# Generated by Django 5.2.6 on 2026-02-23 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_phonenumber_phone_number'),
        ('logistic', '0008_remove_carrier_contacts'),
        ('stock', '0003_remove_warehouse_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='logistic.carrier'),
        ),
        migrations.AddField(
            model_name='contact',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='stock.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carrier__isnull', False), ('warehouse__isnull', True)), models.Q(('carrier__isnull', True), ('warehouse__isnull', False)), _connector='OR'), name='contact_belongs_to_exactly_one_parent'),
        ),
    ]
