# Generated by Django 5.2.6 on 2026-03-11 15:01

import phonenumber_field.modelfields
import phonenumber_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
