# Generated by Django 5.2.6 on 2026-03-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_options_alter_phonenumber_options'),
        ('logistic', '0012_rename_full_name_carrier_organization'),
        ('order', '__first__'),
        ('stock', '0007_warehouse_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact_belongs_to_exactly_one_parent',
        ),
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='order.client'),
        ),
        migrations.AddField(
            model_name='contact',
            name='construction_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='order.constructionobject'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carrier__isnull', False), ('client__isnull', True), ('construction_object__isnull', True), ('warehouse__isnull', True)), models.Q(('carrier__isnull', True), ('client__isnull', True), ('construction_object__isnull', True), ('warehouse__isnull', False)), models.Q(('carrier__isnull', True), ('client__isnull', False), ('construction_object__isnull', True), ('warehouse__isnull', True)), models.Q(('carrier__isnull', True), ('client__isnull', True), ('construction_object__isnull', False), ('warehouse__isnull', True)), _connector='OR'), name='contact_belongs_to_exactly_one_parent'),
        ),
    ]
