# Generated by Django 5.2.6 on 2026-04-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_remove_contact_contact_belongs_to_exactly_one_parent_and_more'),
        ('logistic', '0012_rename_full_name_carrier_organization'),
        ('order', '0002_constructionobject_order_const_custome_6efefd_idx_and_more'),
        ('stock', '0007_warehouse_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact_belongs_to_exactly_one_parent',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='construction_object',
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='order.customer'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(condition=models.Q(('carrier__isnull', False)), fields=['carrier'], name='idx_carrier_not_null'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(condition=models.Q(('warehouse__isnull', False)), fields=['warehouse'], name='idx_warehouse_not_null'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(condition=models.Q(('client__isnull', False)), fields=['client'], name='idx_client_not_null'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(condition=models.Q(('customer__isnull', False)), fields=['customer'], name='idx_customer_not_null'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carrier__isnull', False), ('client__isnull', True), ('customer__isnull', True), ('warehouse__isnull', True)), models.Q(('carrier__isnull', True), ('client__isnull', True), ('customer__isnull', True), ('warehouse__isnull', False)), models.Q(('carrier__isnull', True), ('client__isnull', False), ('customer__isnull', True), ('warehouse__isnull', True)), models.Q(('carrier__isnull', True), ('client__isnull', True), ('customer__isnull', False), ('warehouse__isnull', True)), _connector='OR'), name='contact_belongs_to_exactly_one_parent'),
        ),
    ]
