# Generated by Django 5.2.17 on 2026-09-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_remove_contact_contact_belongs_to_exactly_one_parent_and_more'),
        ('logistic', '0012_rename_full_name_carrier_organization'),
        ('order', '0014_order_order_date'),
        ('repairs', '0001_initial'),
        ('stock', '0008_alter_warehouse_directions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact_belongs_to_exactly_one_parent',
        ),
        migrations.AddField(
            model_name='contact',
            name='repair_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='repairs.repaircompany'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(condition=models.Q(('repair_company__isnull', False)), fields=['repair_company'], name='idx_repair_company_not_null'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carrier__isnull', False), ('client__isnull', True), ('customer__isnull', True), ('repair_company__isnull', True), ('warehouse__isnull', True)), models.Q(('carrier__isnull', True), ('client__isnull', True), ('customer__isnull', True), ('repair_company__isnull', True), ('warehouse__isnull', False)), models.Q(('carrier__isnull', True), ('client__isnull', False), ('customer__isnull', True), ('repair_company__isnull', True), ('warehouse__isnull', True)), models.Q(('carrier__isnull', True), ('client__isnull', True), ('customer__isnull', False), ('repair_company__isnull', True), ('warehouse__isnull', True)), models.Q(('carrier__isnull', True), ('client__isnull', True), ('customer__isnull', True), ('repair_company__isnull', False), ('warehouse__isnull', True)), _connector='OR'), name='contact_belongs_to_exactly_one_parent'),
        ),
    ]
