# Generated by Django 5.2.6 on 2026-01-23 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_number',
            field=models.CharField(blank=True, db_index=True, help_text='Format: 1234 567890', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Passport must be 10 digits (4 for series, 6 for number).', regex='^\\d{4}\\s?\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, help_text='Russian phone number', max_length=18, null=True, validators=[django.core.validators.RegexValidator(message="Format: '+79991234567' or '89991234567'. Exactly 10 digits required after prefix.", regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')]),
        ),
    ]
