# Generated by Django 5.2.6 on 2026-01-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_carrier_full_name_alter_driver_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckcapacity',
            name='capacity',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
