# Generated by Django 5.2.6 on 2026-01-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_truckcapacity_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truckcapacity',
            options={'verbose_name': 'Truck Capacity', 'verbose_name_plural': 'Truck Capacities'},
        ),
        migrations.AlterModelOptions(
            name='trucktype',
            options={'verbose_name': 'Truck Type', 'verbose_name_plural': 'Truck Types'},
        ),
    ]
