# Generated by Django 5.2.6 on 2026-01-26 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_alter_truckcapacity_options_alter_trucktype_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trucktype',
            name='logistic_tr_truck_t_0086d2_idx',
        ),
        migrations.RenameField(
            model_name='trucktype',
            old_name='truck_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_capacity', to='logistic.truckcapacity'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_carrier', to='logistic.carrier'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_type', to='logistic.trucktype'),
        ),
        migrations.AddIndex(
            model_name='trucktype',
            index=models.Index(fields=['type'], name='logistic_tr_type_e0674b_idx'),
        ),
    ]
