# Generated by Django 5.2.6 on 2026-02-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_remove_trucktype_logistic_tr_truck_t_0086d2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trucktype',
            name='logistic_tr_type_e0674b_idx',
        ),
        migrations.RenameField(
            model_name='trucktype',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='type',
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='logistic.trucktype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='logistic.truckcapacity'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='logistic.carrier'),
        ),
        migrations.AddIndex(
            model_name='trucktype',
            index=models.Index(fields=['name'], name='logistic_tr_name_9762de_idx'),
        ),
    ]
