# Generated by Django 5.2.6 on 2026-02-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('logistic', '0006_remove_trucktype_logistic_tr_type_e0674b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriers', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
