# Generated by Django 5.2.6 on 2026-02-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_carrier_contacts_carrier_email_carrier_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='contacts',
        ),
    ]
