# Generated by Django 5.2.6 on 2026-03-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0008_remove_carrier_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckcapacity',
            name='capacity',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
