# Generated by Django 5.2.6 on 2026-03-12 06:02

import phonenumber_field.modelfields
import phonenumber_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_alter_truckcapacity_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
