# Generated by Django 5.2.6 on 2026-03-20 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0010_alter_carrier_phone_alter_driver_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'Перевозчик', 'verbose_name_plural': 'Перевозчики'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'verbose_name': 'Автотранспорт', 'verbose_name_plural': 'Автотранспорт'},
        ),
        migrations.AlterModelOptions(
            name='truckcapacity',
            options={'verbose_name': 'Грузоподъемность', 'verbose_name_plural': 'Грузоподъемность'},
        ),
        migrations.AlterModelOptions(
            name='trucktype',
            options={'verbose_name': 'Тип авто', 'verbose_name_plural': 'Типы авто'},
        ),
        migrations.RemoveIndex(
            model_name='truck',
            name='logistic_tr_carrier_127af1_idx',
        ),
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(db_index=True, help_text='Например: А123ВС77', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Формат: А123ВС77', regex='^[АВЕКМНОРСТУХ]\\d{3}[АВЕКМНОРСТУХ]{2}\\d{2,3}$')]),
        ),
    ]
