# Generated by Django 5.2.6 on 2026-03-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_alter_carrier_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='full_name',
            new_name='organization',
        ),
    ]
