# Generated by Django 5.2.6 on 2026-04-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='constructionobject',
            index=models.Index(fields=['customer'], name='order_const_custome_6efefd_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionobject',
            index=models.Index(fields=['name'], name='order_const_name_2ce527_idx'),
        ),
    ]
