# Generated by Django 5.2.6 on 2026-04-13 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_remove_contact_contact_belongs_to_exactly_one_parent_and_more'),
        ('order', '0002_constructionobject_order_const_custome_6efefd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_from', models.DateTimeField(blank=True, null=True, verbose_name='Доставка с')),
                ('delivery_to', models.DateTimeField(blank=True, null=True, verbose_name='Доставка по')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('created', 'Создан'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='draft', max_length=20, verbose_name='Статус заказа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.client', verbose_name='Клиент')),
                ('contacts', models.ManyToManyField(blank=True, to='contacts.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.customer', verbose_name='Заказчик')),
                ('customer_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.constructionobject', verbose_name='Объект')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
