# Generated by Django 5.2.6 on 2026-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Доставка с'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Доставка по'),
        ),
    ]
