# Generated by Django 5.2.6 on 2026-04-21 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery_from_alter_order_delivery_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upd_pdf',
            field=models.FileField(blank=True, help_text='Загрузите копию УПД (только PDF файлы)', null=True, upload_to='docs/upd/%Y/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='УПД в формате PDF'),
        ),
    ]
