# Generated by Django 5.2.6 on 2026-04-23 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productpallet_options_and_more'),
        ('contacts', '0010_remove_contact_contact_belongs_to_exactly_one_parent_and_more'),
        ('order', '0005_order_upd_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_based_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_at_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(blank=True, through='order.OrderItem', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_date', 'delivery_from', 'delivery_to'], name='order_order_deliver_7fe597_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='order_order_order_i_89d10a_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('piece_based_quantity__isnull', False), ('weight_quantity__isnull', True)), models.Q(('piece_based_quantity__isnull', True), ('weight_quantity__isnull', False)), _connector='OR'), name='exactly_one_quantity_type'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
