# Generated by Django 5.2.6 on 2026-04-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_order_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='samples',
            field=models.BooleanField(default=False, verbose_name='Образцы'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
