# Generated by Django 5.2.6 on 2026-04-28 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_samples_orderitem_price_at_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковка',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pack_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.packtype'),
        ),
    ]
