# Generated by Django 5.2.6 on 2026-05-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_rename_full_name_carrier_organization'),
        ('order', '0008_packtype_orderitem_pack_type'),
        ('stock', '0007_warehouse_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Стоимость доставки', max_digits=10)),
                ('delivery_compensation', models.DecimalField(decimal_places=2, default=0.0, help_text='Оплата за доставку', max_digits=10)),
                ('demurrage', models.DecimalField(decimal_places=2, default=0.0, help_text='Простой на выгрузке', max_digits=10)),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistic.carrier')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistic.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='order.order')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistic.truck')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'Данные доставки',
                'verbose_name_plural': 'Данные доставок',
                'db_table': 'order_delivery',
                'ordering': ['order', 'warehouse'],
                'unique_together': {('order', 'warehouse')},
            },
        ),
    ]
