# Generated by Django 5.2.6 on 2026-05-12 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_salespricehistory_options_and_more'),
        ('contacts', '0010_remove_contact_contact_belongs_to_exactly_one_parent_and_more'),
        ('order', '0009_orderdelivery'),
        ('stock', '0007_warehouse_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_deliver_7fe597_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.warehouse', verbose_name='Склад'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_date', 'client', 'warehouse', 'customer'], name='order_order_deliver_ce3ebe_idx'),
        ),
    ]
