# Generated by Django 5.2.6 on 2026-05-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_rename_full_name_carrier_organization'),
        ('order', '0010_remove_order_order_order_deliver_7fe597_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdelivery',
            options={'ordering': ['-order'], 'verbose_name': 'Данные доставки', 'verbose_name_plural': 'Данные доставок'},
        ),
        migrations.AlterUniqueTogether(
            name='orderdelivery',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='order.order'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['order'], name='order_deliv_order_i_5e9e35_idx'),
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='warehouse',
        ),
    ]
