# Generated by Django 5.2.6 on 2026-08-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderdelivery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('export_order', 'Can export orders')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
