# Generated by Django 5.2.17 on 2026-08-30 10:40

import django.core.validators
import order.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='upd_pdf',
            field=models.FileField(blank=True, help_text='Загрузите копию УПД (только PDF файлы)', null=True, upload_to=order.models.order.upd_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='УПД в формате PDF'),
        ),
    ]
