# Generated by Django 5.2.17 on 2026-09-27 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_upd_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата заявки'),
        ),
    ]
