# Generated by Django 5.2.17 on 2026-08-30 13:40

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='file',
            field=models.FileField(upload_to='docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), common.validators.validate_documentation_file_size]),
        ),
    ]
