# Generated by Django 5.2.6 on 2026-01-22 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'name'], name='carrier_car_is_acti_d4ceeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TruckCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.SmallIntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['capacity'], name='carrier_tru_capacit_abd8a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['truck_type'], name='carrier_tru_truck_t_4e58d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Russian phone number', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message="Format: '+79991234567' or '89991234567'. Exactly 10 digits required after prefix.", regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')])),
                ('passport_number', models.CharField(db_index=True, help_text='Format: 1234 567890', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Passport must be 10 digits (4 for series, 6 for number).', regex='^\\d{4}\\s?\\d{6}$')])),
                ('passport_issue_date', models.DateField(blank=True, help_text='Passport issue date', null=True)),
                ('passport_emitted_by', models.CharField(blank=True, help_text='Passport issuer', max_length=150, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='carrier.carrier')),
            ],
            options={
                'indexes': [models.Index(fields=['carrier', 'full_name'], name='carrier_dri_carrier_02e70d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(db_index=True, help_text='Standard Russian license plate (Cyrillic)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Format: A123BC77 (Use Latin characters A, B, E, K, M, H, O, P, C, T, U, X)', regex='^[ABEKMHOPCTUX]\\d{3}[ABEKMHOPCTUX]{2}\\d{2,3}$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='carrier.carrier')),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='carrier.truckcapacity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='carrier.trucktype')),
            ],
            options={
                'indexes': [models.Index(fields=['carrier'], name='carrier_tru_carrier_7b90d5_idx')],
            },
        ),
    ]
