# Generated by Django 5.2.6 on 2026-03-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AddField(
            model_name='documentation',
            name='tag',
            field=models.CharField(choices=[('МИКСИТИ', 'МИКСИТИ'), ('РИКС', 'РИКС'), ('ОБЩИЕ', 'ОБЩИЕ')], default='МИКСИТИ', max_length=255),
        ),
    ]
