# Generated by Django 5.2.6 on 2026-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_documentation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
